definitions:
  helperStruct.Address:
    properties:
      city:
        type: string
      district:
        type: string
      house_number:
        type: string
      id:
        type: integer
      isdefault:
        type: boolean
      landmark:
        type: string
      pincode:
        type: integer
      street:
        type: string
    required:
    - city
    - district
    - house_number
    - landmark
    - pincode
    - street
    type: object
  helperStruct.Coupons:
    properties:
      code:
        type: string
      discountmaximumamount:
        type: number
      discountpercent:
        type: number
      expirationdate:
        type: string
      minimumpurchaseamount:
        type: number
    type: object
  helperStruct.CreateAdmin:
    properties:
      email:
        type: string
      isSuper:
        type: boolean
      name:
        type: string
      password:
        type: string
    required:
    - email
    - isSuper
    - name
    - password
    type: object
  helperStruct.LoginReq:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  helperStruct.UserReq:
    properties:
      email:
        type: string
      mobile:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - mobile
    - name
    type: object
  response.Response:
    properties:
      data: {}
      error: {}
      message:
        type: string
      stastuscode:
        type: integer
    type: object
  response.UserData:
    properties:
      email:
        type: string
      id:
        type: integer
      mobile:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /addaddress:
    post:
      consumes:
      - application/json
      operationId: user-add-address
      parameters:
      - description: User address
        in: body
        name: user_address
        required: true
        schema:
          $ref: '#/definitions/helperStruct.Address'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: user add address
  /addcoupontocart/{coupon_id}:
    patch:
      consumes:
      - application/json
      description: User can add coupon to the cart
      operationId: applay-coupon-to-cart
      parameters:
      - description: coupon_id
        in: path
        name: coupon_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: User can add a coupon to the cart
      tags:
      - Cart
  /addtocart/{product_item_id}:
    post:
      consumes:
      - application/json
      description: User can add product item to the cart
      operationId: add-to-cart
      parameters:
      - description: product_item_id
        in: path
        name: product_item_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: User can add a product item to the cart
      tags:
      - Cart
  /addtofav/{productId}:
    post:
      consumes:
      - application/json
      description: User can add product item to favourites
      operationId: add-to-favourites
      parameters:
      - description: ID of the product item to be added to wishlist
        in: path
        name: productId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: User can add product item to favourites
      tags:
      - Favourites
  /admin/adminlogin:
    post:
      consumes:
      - application/json
      description: Admin login
      operationId: admin-login
      parameters:
      - description: Admin login credentials
        in: body
        name: admin_credentials
        required: true
        schema:
          $ref: '#/definitions/helperStruct.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: Admin Login
      tags:
      - Admin
  /admin/adminlogout:
    post:
      consumes:
      - application/json
      description: Logs out a logged-in admin from the E-commerce web api admin panel
      operationId: admin-logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
      summary: Admin Logout
      tags:
      - Admin
  /admin/blockuser/{id}:
    patch:
      consumes:
      - application/json
      description: Admins can block users
      operationId: block-users
      parameters:
      - description: ID of the user to be blocked
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: Admin can bolock users
      tags:
      - Admin
  /admin/createadmin:
    post:
      consumes:
      - application/json
      description: Super admin can create a new admin from admin panel.
      operationId: create-admin
      parameters:
      - description: New Admin details
        in: body
        name: admin_details
        required: true
        schema:
          $ref: '#/definitions/helperStruct.CreateAdmin'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: Create a new admin from admin panel
      tags:
      - Admin
  /admin/createcoupon/:
    post:
      consumes:
      - application/json
      description: Admin can create new coupons
      operationId: create-coupon
      parameters:
      - description: details of new coupon to be created
        in: body
        name: new_coupon_details
        required: true
        schema:
          $ref: '#/definitions/helperStruct.Coupons'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: Admin can create new coupon
      tags:
      - Coupon
  /admin/deletecoupon/{couponId}:
    delete:
      consumes:
      - application/json
      description: Admin can delete existing coupon
      operationId: delete-coupon
      parameters:
      - description: details of coupon to be updated
        in: path
        name: coupon_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: Admin can delete existing coupon
      tags:
      - Coupon
  /admin/downloadsales/:
    get:
      consumes:
      - application/json
      description: Admin can download sales report in .csv format
      operationId: download-sales-report
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: Admin can download sales report
      tags:
      - Admin
  /admin/findall:
    get:
      consumes:
      - application/json
      description: Admin can find all registered users
      operationId: find-all-users
      parameters:
      - description: Page number for pagination
        in: query
        name: page
        type: integer
      - description: Number of items to retrieve per page
        in: query
        name: limit
        type: integer
      - description: Search query string
        in: query
        name: query
        type: string
      - description: Filter criteria for the users
        in: query
        name: filter
        type: string
      - description: Sorting criteria for the users
        in: query
        name: sort_by
        type: string
      - description: Sorting in descending order
        in: query
        name: sort_desc
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: Admin can find all registered users
      tags:
      - Admin
  /admin/finduser/{id}:
    get:
      consumes:
      - application/json
      description: Admins can find users with id
      operationId: find-users
      parameters:
      - description: ID of the user to be found
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: Admin can find a user
      tags:
      - Admin
  /admin/getdashboard:
    get:
      consumes:
      - application/json
      description: Admin can access dashboard and view details regarding orders, products,
        etc.
      operationId: admin-dashboard
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: Admin Dashboard
      tags:
      - Admin
  /admin/salesreport/:
    get:
      consumes:
      - application/json
      description: Admin can view the sales report
      operationId: view-sales-report
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: Admin can view sales report
      tags:
      - Admin
  /admin/unblockuser/{id}:
    patch:
      consumes:
      - application/json
      description: Admins can block users
      operationId: unblock-users
      parameters:
      - description: ID of the user to be blocked
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: Admin can unbolock a blocked user
      tags:
      - Admin
  /admin/updatecoupen/{couponId}:
    patch:
      consumes:
      - application/json
      description: Admin can update existing coupon
      operationId: update-coupon
      parameters:
      - description: Coupon ID
        in: path
        name: couponId
        required: true
        type: string
      - description: details of coupon to be updated
        in: body
        name: coupon_details
        required: true
        schema:
          $ref: '#/definitions/helperStruct.Coupons'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: Admin can update existing coupon
      tags:
      - Coupon
  /admin/viewcoupon/{couponId}:
    get:
      consumes:
      - application/json
      description: Admins and users can see coupon with id
      operationId: view-coupon-by-id
      parameters:
      - description: coupon_id
        in: path
        name: coupon_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: Admins and users can see coupon with coupon id
      tags:
      - Coupon
  /admin/viewcoupons/:
    get:
      consumes:
      - application/json
      description: Admins and users can see all available coupons
      operationId: view-coupons
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: Admins and users can see all available coupons
      tags:
      - Coupon
  /listcart:
    get:
      consumes:
      - application/json
      description: User can view cart and cart items
      operationId: view-cart
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: User can view cart items and total
      tags:
      - Cart
  /logout:
    get:
      operationId: user-logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: user logout
  /removecoupon:
    patch:
      consumes:
      - application/json
      description: User can add coupon to the cart
      operationId: remove-coupon-to-cart
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: User can remove the coupon that added to the cart
      tags:
      - Cart
  /removefromcart/{product_item_id}:
    delete:
      consumes:
      - application/json
      description: User can remove product from cart
      operationId: remove-from-cart
      parameters:
      - description: product_item_id
        in: path
        name: product_item_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: Remove a product from the cart
      tags:
      - Cart
  /removefromfav/{productId}:
    delete:
      consumes:
      - application/json
      description: User can remove product item from favourites
      operationId: remove-from-favourites
      parameters:
      - description: ID of the product item to be added to wishlist
        in: path
        name: productId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: User can remove product item from favourites
      tags:
      - Favourites
  /signup:
    post:
      consumes:
      - application/json
      operationId: user-signup
      parameters:
      - description: User Data
        in: body
        name: user_details
        required: true
        schema:
          $ref: '#/definitions/helperStruct.UserReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: user signup
  /userlogin:
    post:
      consumes:
      - application/json
      operationId: user-login
      parameters:
      - description: User Data
        in: body
        name: user_details
        required: true
        schema:
          $ref: '#/definitions/helperStruct.LoginReq'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: user login
  /viewfav/:
    get:
      consumes:
      - application/json
      description: User view product items in favourites
      operationId: view-favourites
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: User can view items in favourites
      tags:
      - favourites
swagger: "2.0"
